apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim: 
            claimName: persistent-volume-claim
      containers:
        - name: docker-container1
          image: us-central1-docker.pkg.dev/cloud-k8-assignment/kubernetes-artifact-registry/freya-docker-1
          ports:
            - containerPort: 6000
              name: "http-server"
          volumeMounts:
            - mountPath: /freya_PV_dir
              name: pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6000