apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: persistent-volume-claim
      containers:
        - name: docker-container2
          image: us-central1-docker.pkg.dev/cloud-k8-assignment/kubernetes-artifact-registry/freya-docker-2
          ports:
            - containerPort: 10000 
              name: "http-server"
          volumeMounts:
            - mountPath: /freya_PV_dir
              name: pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 10000